// Generated by scripts/generate-script-api.js from the JSDoc in packages/bruno-js. Do not edit.
/// <reference types="chai" />

/**
 * Bruno's scripting API: variables, environments, cookies, the collection runner, and sending
 * requests from a script.
 *
 * @context pre-request post-response tests grpc:before-call-start grpc:before-message-send grpc:after-message-receive grpc:after-call-end
 * @category bru
 */
export declare const bru: Bru;

/**
 * The HTTP request.
 *
 * @context pre-request post-response tests
 * @category req
 */
export declare const req: Request;

/**
 * The HTTP response.
 *
 * @context post-response tests
 * @category res
 */
export declare const res: Response;

/**
 * Define a test. Its result shows in the Tests tab of the response pane.
 *
 * A test passes when `fn` returns, or resolves, without throwing; any error or failed assertion
 * fails it. Tests run in the order they are declared, and the script waits for async tests to
 * settle before it finishes.
 *
 * @param name - The test's name, as shown in the results.
 * @param fn - The test body. Make it `async` to await inside it.
 * @returns A promise that settles once the test has run. It never rejects.
 * @example
 * test('responds with 200', () => {
 *   expect(res.getStatus()).to.equal(200);
 * });
 * @context pre-request post-response tests grpc:before-call-start grpc:before-message-send grpc:after-message-receive grpc:after-call-end
 * @category Tests & assertions
 */
export declare function test(name: string, fn: () => void | Promise<void>): Promise<void>;

/**
 * Chai's BDD assertion style: `expect(value).to.equal(expected)`.
 *
 * See https://www.chaijs.com/api/bdd/ for every assertion.
 *
 * @example
 * expect(res.getStatus()).to.equal(200);
 * expect(res.body).to.have.property('id');
 * @context pre-request post-response tests grpc:before-call-start grpc:before-message-send grpc:after-message-receive grpc:after-call-end
 * @category Tests & assertions
 */
export declare const expect: Chai.ExpectStatic;

/**
 * Chai's assert style: `assert.equal(actual, expected)`.
 *
 * See https://www.chaijs.com/api/assert/ for every assertion.
 *
 * @example
 * assert.equal(res.getStatus(), 200);
 * @context pre-request post-response tests grpc:before-call-start grpc:before-message-send grpc:after-message-receive grpc:after-call-end
 * @category Tests & assertions
 */
export declare const assert: Chai.AssertStatic;

/**
 * Bruno's scripting API, available to every script as `bru`: variables at every scope, the
 * collection runner, cookies, and sending requests from a script.
 *
 * @category bru
 */
export interface Bru {
  /**
   * Send an HTTP request from the script and resolve with its response.
   *
   * Takes an axios request config (`method`, `url`, `headers`, `data`, `timeout`, …) or just a
   * URL. The request goes through the collection's proxy and certificate settings. Without a
   * callback the promise rejects on a network error or a 4xx/5xx status; with one, the callback
   * gets `(error, response)` instead, and `error.status` holds the HTTP status.
   *
   * @param config - An axios request config, or the URL to GET.
   * @param callback - Called with `(error, response)` once the request settles.
   * @returns The response.
   * @example
   * const response = await bru.sendRequest({
   *   method: 'POST',
   *   url: 'https://echo.usebruno.com',
   *   headers: { 'Content-Type': 'application/json' },
   *   data: { hello: 'bruno' }
   * });
   * bru.setVar('echoed', response.data);
   * @category Requests
   */
  sendRequest(config: string | object, callback?: (error: any, response: SendRequestResponse | null) => void | Promise<void>): Promise<SendRequestResponse>;
  /**
   * The cookies of the current request's URL, read from and written to the app's cookie jar.
   *
   * Reads are synchronous; writes return a promise. `bru.cookies.jar()` reaches cookies of any URL.
   *
   * @example
   * const sessionId = bru.cookies.get('sid');
   * await bru.cookies.upsert({ key: 'lang', value: 'en' });
   * @category Cookies
   */
  cookies: CookieList;
  /**
   * Steer the collection runner: skip the current request, stop the run, or choose what runs next.
   *
   * These only take effect when the request runs as part of a collection or folder run.
   *
   * @example
   * if (!bru.getEnvVar('token')) {
   *   bru.runner.skipRequest();
   * }
   * @category Runner
   */
  runner: Runner;
  /**
   * Helpers for formatting payloads.
   *
   * @example
   * req.setBody(bru.utils.minifyJson(req.getBody({ raw: true })), { raw: true });
   * @runtime nodevm
   * @category Utilities
   */
  utils: ScriptUtils;
  /**
   * Run another request of the collection and resolve with its response.
   *
   * The request runs with its own scripts, variables and auth, as if it were sent from the app.
   * WebSocket and gRPC requests can't be run this way and resolve with `status: 'skipped'`.
   *
   * @param requestPathName - The request's path from the collection root, with or without the file extension, such as `'auth/login'`.
   * @returns The response.
   * @example
   * const login = await bru.runRequest('auth/login');
   * bru.setVar('token', login.data.token);
   * @context pre-request post-response tests
   * @category Requests
   */
  runRequest(requestPathName: string): Promise<RunRequestResponse>;
  /**
   * Get the `test()` results of the current script so far.
   *
   * @returns The pass and fail counts and one entry per test.
   * @example
   * const { summary } = await bru.getTestResults();
   * console.log(`${summary.passed}/${summary.total} passed`);
   * @category Tests
   */
  getTestResults(): Promise<TestResults>;
  /**
   * Get the results of the request's Assert tab.
   *
   * Assertions run after the post-response script and before the tests, so only tests see them.
   *
   * @returns The pass and fail counts and one entry per assertion.
   * @example
   * const { summary } = await bru.getAssertionResults();
   * test('all assertions pass', () => expect(summary.failed).to.equal(0));
   * @context tests
   * @category Tests
   */
  getAssertionResults(): Promise<AssertionResults>;
  /**
   * The gRPC call the hook runs in: its request and, once the server answers, its response.
   *
   * @context grpc:before-call-start grpc:before-message-send grpc:after-message-receive grpc:after-call-end
   * @category gRPC
   */
  grpc: Grpc;
  /**
   * Replace the `{{variable}}` placeholders in a string, or in every string of an object.
   *
   * Variables resolve the same way they do in a request, from every scope, and
   * `{{process.env.NAME}}` reads a process environment variable.
   *
   * @param strOrObj - The string, or an object whose string values to interpolate.
   * @returns The interpolated string, or a new object.
   * @example
   * const url = bru.interpolate('{{baseUrl}}/users/{{userId}}');
   * @category Utilities
   */
  interpolate(strOrObj: string | object): any;
  /**
   * Get the path of the collection's folder on disk.
   *
   * @returns The collection's directory.
   * @category Collection
   */
  cwd(): string;
  /**
   * Get the name of the selected environment.
   *
   * @returns The environment's name, or `undefined` when none is selected.
   * @category Environment
   */
  getEnvName(): string | undefined;
  /**
   * Read a process environment variable, including those from the collection's `.env` file.
   *
   * @param key - The variable's name.
   * @returns The value, or `undefined` when it is not set.
   * @example
   * const apiKey = bru.getProcessEnv('API_KEY');
   * @category Environment
   */
  getProcessEnv(key: string): string | undefined;
  /**
   * Check whether the selected environment defines a variable.
   *
   * @param key - The variable's name.
   * @returns `true` when the variable exists, even with an empty value.
   * @category Environment
   */
  hasEnvVar(key: string): boolean;
  /**
   * Get the value of a variable of the selected environment.
   *
   * `{{placeholders}}` in the value are interpolated.
   *
   * @param key - The variable's name.
   * @returns The value, or `undefined` when it is not set.
   * @example
   * const baseUrl = bru.getEnvVar('baseUrl');
   * @category Environment
   */
  getEnvVar(key: string): any;
  /**
   * Set a variable of the selected environment, creating it when it doesn't exist.
   *
   * The change is visible to the requests that run after this one.
   *
   * @param key - The variable's name: letters, digits, `-`, `_` and `.` only.
   * @param value - The value. Objects and arrays are stored as they are.
   * @example
   * bru.setEnvVar('token', res.body.token);
   * @category Environment
   */
  setEnvVar(key: string, value: any): void;
  /**
   * Delete a variable from the selected environment.
   *
   * @param key - The variable's name. Nothing happens when it doesn't exist.
   * @category Environment
   */
  deleteEnvVar(key: string): void;
  /**
   * Get every variable of the selected environment.
   *
   * @returns A copy of the variables, by name. Values are not interpolated.
   * @category Environment
   */
  getAllEnvVars(): Record<string, any>;
  /**
   * Delete every variable of the selected environment.
   *
   * @category Environment
   */
  deleteAllEnvVars(): void;
  /**
   * Check whether the selected global environment defines a variable.
   *
   * @param key - The variable's name.
   * @returns `true` when the variable exists.
   * @category Global environment
   */
  hasGlobalEnvVar(key: string): boolean;
  /**
   * Get the value of a variable of the selected global environment.
   *
   * `{{placeholders}}` in the value are interpolated.
   *
   * @param key - The variable's name.
   * @returns The value, or `undefined` when it is not set.
   * @category Global environment
   */
  getGlobalEnvVar(key: string): any;
  /**
   * Set a variable of the selected global environment, creating it when it doesn't exist.
   *
   * @param key - The variable's name: letters, digits, `-`, `_` and `.` only.
   * @param value - The value.
   * @example
   * bru.setGlobalEnvVar('region', 'eu-west-1');
   * @category Global environment
   */
  setGlobalEnvVar(key: string, value: any): void;
  /**
   * Delete a variable from the selected global environment.
   *
   * @param key - The variable's name. Nothing happens when it doesn't exist.
   * @category Global environment
   */
  deleteGlobalEnvVar(key: string): void;
  /**
   * Get every variable of the selected global environment.
   *
   * @returns A copy of the variables, by name. Values are not interpolated.
   * @category Global environment
   */
  getAllGlobalEnvVars(): Record<string, any>;
  /**
   * Delete every variable of the selected global environment.
   *
   * @category Global environment
   */
  deleteAllGlobalEnvVars(): void;
  /**
   * Read a value of an OAuth2 credential the collection has fetched.
   *
   * @param key - The credential variable, such as `'$oauth2.<credentialId>.access_token'`.
   * @returns The value, or `undefined` when there is none.
   * @example
   * const token = bru.getOauth2CredentialVar('$oauth2.my-auth.access_token');
   * @category OAuth2
   */
  getOauth2CredentialVar(key: string): any;
  /**
   * Discard a stored OAuth2 credential, so the next request that uses it fetches a new token.
   *
   * Its values read as `undefined` for the rest of the script.
   *
   * @param credentialId - The credential's ID.
   * @category OAuth2
   */
  resetOauth2Credential(credentialId: string): void;
  /**
   * Check whether a runtime variable exists.
   *
   * @param key - The variable's name.
   * @returns `true` when the variable exists.
   * @category Runtime variables
   */
  hasVar(key: string): boolean;
  /**
   * Set a runtime variable, creating it when it doesn't exist.
   *
   * Runtime variables last until the app is closed.
   *
   * @param key - The variable's name: letters, digits, `-`, `_` and `.` only.
   * @param value - The value.
   * @example
   * bru.setVar('userId', res.body.id);
   * @category Runtime variables
   */
  setVar(key: string, value: any): void;
  /**
   * Get the value of a runtime variable.
   *
   * `{{placeholders}}` in the value are interpolated.
   *
   * @param key - The variable's name.
   * @returns The value, or `undefined` when it is not set.
   * @example
   * const userId = bru.getVar('userId');
   * @category Runtime variables
   */
  getVar(key: string): any;
  /**
   * Delete a runtime variable.
   *
   * @param key - The variable's name. Nothing happens when it doesn't exist.
   * @category Runtime variables
   */
  deleteVar(key: string): void;
  /**
   * Delete every runtime variable.
   *
   * @category Runtime variables
   */
  deleteAllVars(): void;
  /**
   * Get every runtime variable.
   *
   * @returns A copy of the variables, by name. Values are not interpolated.
   * @category Runtime variables
   */
  getAllVars(): Record<string, any>;
  /**
   * Get the value of a collection variable.
   *
   * `{{placeholders}}` in the value are interpolated.
   *
   * @param key - The variable's name.
   * @returns The value, or `undefined` when it is not set.
   * @category Collection variables
   */
  getCollectionVar(key: string): any;
  /**
   * Set a collection variable, creating it when it doesn't exist.
   *
   * @param key - The variable's name: letters, digits, `-`, `_` and `.` only.
   * @param value - The value.
   * @category Collection variables
   */
  setCollectionVar(key: string, value: any): void;
  /**
   * Check whether a collection variable exists.
   *
   * @param key - The variable's name.
   * @returns `true` when the variable exists.
   * @category Collection variables
   */
  hasCollectionVar(key: string): boolean;
  /**
   * Delete a collection variable.
   *
   * @param key - The variable's name. Nothing happens when it doesn't exist.
   * @category Collection variables
   */
  deleteCollectionVar(key: string): void;
  /**
   * Delete every collection variable.
   *
   * @category Collection variables
   */
  deleteAllCollectionVars(): void;
  /**
   * Get every collection variable.
   *
   * @returns A copy of the variables, by name. Values are not interpolated.
   * @category Collection variables
   */
  getAllCollectionVars(): Record<string, any>;
  /**
   * Get the value of a variable of the request's folder. Folder variables are read-only in scripts.
   *
   * @param key - The variable's name.
   * @returns The interpolated value, or `undefined` when it is not set.
   * @category Folder and request variables
   */
  getFolderVar(key: string): any;
  /**
   * Get the value of a variable of the request itself. Request variables are read-only in scripts.
   *
   * @param key - The variable's name.
   * @returns The interpolated value, or `undefined` when it is not set.
   * @category Folder and request variables
   */
  getRequestVar(key: string): any;
  /**
   * Choose the request the collection runner runs next, by its name.
   *
   * @param nextRequest - The request's name, or `null` to end the run.
   * @deprecated Use `bru.runner.setNextRequest()`.
   * @category Runner
   */
  setNextRequest(nextRequest: string | null): void;
  /**
   * Wait for a number of milliseconds.
   *
   * @param ms - How long to wait.
   * @returns Resolves once the time has passed.
   * @example
   * await bru.sleep(1000);
   * @category Utilities
   */
  sleep(ms: number): Promise<void>;
  /**
   * Get the name of the collection.
   *
   * @returns The collection's name.
   * @category Collection
   */
  getCollectionName(): string;
  /**
   * Check whether the script runs in Safe Mode, the sandbox without Node.js modules or file access.
   *
   * @returns `true` in Safe Mode, `false` in Developer Mode.
   * @category Utilities
   */
  isSafeMode(): boolean;
}

/**
 * The request about to be sent (pre-request), or the one that was sent (post-response and tests).
 *
 * Read and change the URL, method, headers, body and settings. Changes only take effect in a
 * pre-request script, before the request goes out. Variables are interpolated after the
 * pre-request script runs, so there its values still contain their `{{variables}}`.
 *
 * @category req
 */
export interface Request {
  /**
   * The request URL, as it was when the script started.
   *
   * @category URL
   */
  readonly url: string;
  /**
   * The HTTP method, as it was when the script started.
   *
   * @category Method
   */
  readonly method: string;
  /**
   * The request headers, as a `{ name: value }` object. Use `req.setHeader()` or
   * `req.headerList` to change them.
   *
   * @category Headers
   */
  readonly headers: Record<string, any>;
  /**
   * The request timeout in milliseconds, as it was when the script started.
   *
   * @category Settings
   */
  readonly timeout: number | undefined;
  /**
   * The request's name, as shown in the sidebar.
   *
   * @category Info
   */
  readonly name: string;
  /**
   * The request's path parameters. `req.getPathParams()` returns a copy.
   *
   * @category URL
   */
  readonly pathParams: PathParam[] | undefined;
  /**
   * The request's tags.
   *
   * @category Info
   */
  readonly tags: string[];
  /**
   * The request headers as a list: read, add, change and remove headers, disabled ones included.
   *
   * Keys match case-insensitively. Changes apply to the request that is sent.
   *
   * @example
   * req.headerList.upsert({ key: 'Authorization', value: `Bearer ${bru.getVar('token')}` });
   * req.headerList.remove('X-Debug');
   * @category Headers
   */
  readonly headerList: HeaderList;
  /**
   * The request body, parsed when the content type is JSON. Use `req.setBody()` to change it.
   *
   * @category Body
   */
  body: any;
  /**
   * Get the request URL.
   *
   * @returns The URL. In a pre-request script its `{{variables}}` are not interpolated yet.
   * @category URL
   */
  getUrl(): string;
  /**
   * Change the request URL.
   *
   * @param url - The new URL.
   * @example
   * req.setUrl(`${bru.getEnvVar('baseUrl')}/v2/users`);
   * @category URL
   */
  setUrl(url: string): void;
  /**
   * Get the host of the request URL, with the port when it has one.
   *
   * @returns The host, such as `'api.example.com:8080'`, or `''` when the URL is invalid.
   * @category URL
   */
  getHost(): string;
  /**
   * Get the path of the request URL, with the path parameters filled in.
   *
   * @returns The path, such as `'/users/42'`, or `''` when the URL is invalid.
   * @category URL
   */
  getPath(): string;
  /**
   * Get the query string of the request URL.
   *
   * @returns The query string without the leading `?`, or `''` when there is none.
   * @category URL
   */
  getQueryString(): string;
  /**
   * Get the HTTP method.
   *
   * @returns The method, such as `'GET'`.
   * @category Method
   */
  getMethod(): string;
  /**
   * Get the kind of authentication the request uses.
   *
   * @returns The auth mode.
   * @category Auth
   */
  getAuthMode(): "oauth2" | "oauth1" | "bearer" | "basic" | "apikey" | "awsv4" | "digest" | "wsse" | "none";
  /**
   * Change the HTTP method.
   *
   * @param method - The new method, such as `'POST'`.
   * @category Method
   */
  setMethod(method: string): void;
  /**
   * Get the request headers.
   *
   * @returns The headers object, by name. Changing it changes the request.
   * @category Headers
   */
  getHeaders(): Record<string, any>;
  /**
   * Replace all the request headers, including those set at collection and folder level.
   *
   * @param headers - The new headers, by name.
   * @category Headers
   */
  setHeaders(headers: Record<string, any>): void;
  /**
   * Remove several headers, including default headers such as `User-Agent`.
   *
   * @param headers - The names of the headers to remove.
   * @category Headers
   */
  deleteHeaders(headers: string[]): void;
  /**
   * Get the value of a request header.
   *
   * The name matches exactly; use `req.headerList.get()` for a case-insensitive lookup.
   *
   * @param name - The header's name.
   * @returns The value, or `undefined` when the header is not set.
   * @category Headers
   */
  getHeader(name: string): any;
  /**
   * Set a request header, replacing a header of the same name.
   *
   * @param name - The header's name.
   * @param value - The header's value.
   * @example
   * req.setHeader('Authorization', `Bearer ${bru.getVar('token')}`);
   * @category Headers
   */
  setHeader(name: string, value: any): void;
  /**
   * Remove a request header, including default headers such as `User-Agent`.
   *
   * @param name - The header's name.
   * @category Headers
   */
  deleteHeader(name: string): void;
  /**
   * Get the request body.
   *
   * A JSON body is returned parsed; pass `{ raw: true }` for the string that is sent.
   *
   * @param options - `raw: true` returns the body as it is sent.
   * @returns The body.
   * @category Body
   */
  getBody(options?: { raw?: boolean; }): any;
  /**
   * Replace the request body.
   *
   * With a JSON content type, an object is serialized for you. Pass `{ raw: true }` to send
   * `data` exactly as given.
   *
   * @param data - The new body.
   * @param options - `raw: true` skips JSON serialization.
   * @example
   * req.setBody({ ...req.getBody(), requestedAt: Date.now() });
   * @category Body
   */
  setBody(data: any, options?: { raw?: boolean; }): void;
  /**
   * Set how many redirects the request may follow.
   *
   * @param maxRedirects - The limit. `0` disables following redirects.
   * @category Settings
   */
  setMaxRedirects(maxRedirects: number): void;
  /**
   * Get the request timeout.
   *
   * @returns The timeout in milliseconds.
   * @category Settings
   */
  getTimeout(): number | undefined;
  /**
   * Set the request timeout.
   *
   * @param timeout - The timeout in milliseconds.
   * @category Settings
   */
  setTimeout(timeout: number): void;
  /**
   * Handle the request failing to get a response, such as a connection error or a timeout.
   *
   * Variables the handler sets are kept, as they are for a script.
   *
   * @param callback - Called with the error.
   * @example
   * req.onFail((error) => {
   *   console.error('request failed', error.message);
   * });
   * @context pre-request
   * @runtime nodevm
   * @category Errors
   */
  onFail(callback: (error: any) => void | Promise<void>): void;
  /**
   * Keep the response body as a string instead of parsing it as JSON.
   *
   * @context pre-request
   * @category Body
   */
  disableParsingResponseJson(): void;
  /**
   * Get how the request is being run.
   *
   * @returns `'standalone'` when sent on its own from the app, `'runner'` in a collection run, `'cli'` from the Bruno CLI.
   * @category Info
   */
  getExecutionMode(): "standalone" | "runner" | "cli";
  /**
   * Get the request's name, as shown in the sidebar.
   *
   * @returns The name.
   * @category Info
   */
  getName(): string;
  /**
   * Get the request's path parameters.
   *
   * @returns A copy of the parameters, in URL order.
   * @category URL
   */
  getPathParams(): PathParam[];
  /**
   * Get the request's tags.
   *
   * @returns The tags.
   * @category Info
   */
  getTags(): string[];
}

/**
 * The response to the request.
 *
 * `res` is also a function: `res('data.items[0].id')` queries the response body with a path
 * expression, the same as `res.body.data.items[0].id` but `undefined` instead of an error when a
 * step is missing.
 *
 * @category res
 */
export interface Response {
  /**
   * Query the response body with a path expression.
   *
   * @param path - Dot path into the body. `..` searches at any depth, `[0]` indexes an array and `[?]` filters or maps an array with the next function or object in `filters`.
   * @param filters - One predicate, mapper or `{ key: value }` match object per `[?]` in the path.
   * @returns The value at the path, or `undefined` when there is none.
   * @example
   * const id = res('data.items[0].id');
   * const ids = res('..items[?].id', (item) => item.active);
   */
  (path: string, ...filters: (object | ((item: any) => any))[]): any;
  /**
   * The HTTP status code.
   *
   * @category Status
   */
  readonly status: number | null;
  /**
   * The HTTP status text, such as `'OK'`.
   *
   * @category Status
   */
  readonly statusText: string | null;
  /**
   * The response headers, by lower-case name. A repeated header, such as `set-cookie`, has an
   * array of values.
   *
   * @category Headers
   */
  readonly headers: Record<string, any> | null;
  /**
   * The response body, parsed when it is JSON. Use `res.setBody()` to change it.
   *
   * @category Body
   */
  readonly body: any;
  /**
   * How long the request took, in milliseconds.
   *
   * @category Info
   */
  readonly responseTime: number | null;
  /**
   * The URL the response came from, after any redirects.
   *
   * @category Info
   */
  readonly url: string | null;
  /**
   * The response headers as a read-only list, with case-insensitive lookups.
   *
   * @example
   * const contentType = res.headerList.get('content-type');
   * @category Headers
   */
  readonly headerList: ReadOnlyHeaderList;
  /**
   * Get the HTTP status code.
   *
   * @returns The status code.
   * @example
   * test('responds with 200', () => expect(res.getStatus()).to.equal(200));
   * @category Status
   */
  getStatus(): number | null;
  /**
   * Get the HTTP status text.
   *
   * @returns The status text, such as `'OK'`.
   * @category Status
   */
  getStatusText(): string | null;
  /**
   * Get the value of a response header, whatever the case of `name`.
   *
   * @param name - The header's name.
   * @returns The value, an array of values for a repeated header, or `undefined` when the header is absent.
   * @example
   * const contentType = res.getHeader('Content-Type');
   * @category Headers
   */
  getHeader(name: string): any;
  /**
   * Get the response headers.
   *
   * @returns The headers, by lower-case name.
   * @category Headers
   */
  getHeaders(): Record<string, any> | null;
  /**
   * Get the response body.
   *
   * @returns The body, parsed when it is JSON.
   * @example
   * const { token } = res.getBody();
   * @category Body
   */
  getBody(): any;
  /**
   * Get how long the request took.
   *
   * @returns The time in milliseconds.
   * @category Info
   */
  getResponseTime(): number | null;
  /**
   * Get the URL the response came from, after any redirects.
   *
   * @returns The URL.
   * @category Info
   */
  getUrl(): string | null;
  /**
   * Replace the response body, as later scripts, tests and the response pane see it.
   *
   * @param data - The new body. It is copied, so later changes to `data` don't affect it.
   * @example
   * res.setBody({ ...res.getBody(), token: '[redacted]' });
   * @category Body
   */
  setBody(data: any): void;
  /**
   * Get the size of the response.
   *
   * @returns The header, body and total sizes in bytes.
   * @category Info
   */
  getSize(): ResponseSize;
  /**
   * Get the response body as the raw bytes received.
   *
   * @returns A Node.js `Buffer` of the body.
   * @runtime nodevm
   * @category Body
   */
  getDataBuffer(): Uint8Array<ArrayBufferLike> | null;
}

/**
 * The response of a request sent with `bru.sendRequest()`.
 *
 * @category bru
 */
export interface SendRequestResponse {
  /**
   * - The HTTP status code.
   */
  status: number;
  /**
   * - The HTTP status text.
   */
  statusText: string;
  /**
   * - The response headers, with lower-case names.
   */
  headers: Record<string, string | string[]>;
  /**
   * - The response body, parsed as JSON when it is JSON.
   */
  data: any;
}

/**
 * The cookies of the current request's URL, as a list of {@link Cookie} entries.
 *
 * Reads come straight from the app's cookie jar. Writes return a promise, or call the callback
 * when one is passed. `jar()` reaches the cookies of any URL.
 *
 * @category bru
 */
export interface CookieList {
  /**
   * Set a cookie for the current request's URL. The same as `upsert()`.
   *
   * @param cookieObj - The cookie, with at least `key` and `value`.
   * @param callback - Called once the cookie is set. Without it, a promise is returned.
   * @returns A promise when no callback is given.
   * @category Write
   * @example
   * // Promise usage
   * await bru.cookies.add({ key: 'lang', value: 'en' });
   *
   * // Callback usage
   * bru.cookies.add({ key: 'lang', value: 'en' }, (err) => { if (err) throw err; });
   */
  add(cookieObj: CookieInput, callback?: (error?: Error | undefined) => void): void | Promise<void>;
  /**
   * Set a cookie for the current request's URL, replacing a cookie of the same name.
   *
   * Rejects when `cookieObj` is not an object.
   *
   * @param cookieObj - The cookie, with at least `key` and `value`.
   * @param callback - Called once the cookie is set. Without it, a promise is returned.
   * @returns A promise when no callback is given.
   * @category Write
   * @example
   * await bru.cookies.upsert({ key: 'sid', value: 'abc123', secure: true });
   */
  upsert(cookieObj: CookieInput, callback?: (error?: Error | undefined) => void): void | Promise<void>;
  /**
   * Delete a cookie of the current request's URL by name. Nothing happens when there is none.
   *
   * @param name - The cookie's name.
   * @param callback - Called once the cookie is deleted. Without it, a promise is returned.
   * @returns A promise when no callback is given.
   * @category Write
   * @example
   * await bru.cookies.remove('sid');
   */
  remove(name: string, callback?: (error?: Error | undefined) => void): void | Promise<void>;
  /**
   * Delete every cookie of the current request's URL.
   *
   * Cookies of other domains and paths are kept; `jar().clear()` deletes those too.
   *
   * @param callback - Called once the cookies are deleted. Without it, a promise is returned.
   * @returns A promise when no callback is given.
   * @category Write
   */
  clear(callback?: (error?: Error | undefined) => void): void | Promise<void>;
  /**
   * Delete a cookie of the current request's URL by name. The same as `remove()`.
   *
   * @param name - The cookie's name.
   * @param callback - Called once the cookie is deleted. Without it, a promise is returned.
   * @returns A promise when no callback is given.
   * @category Write
   * @example
   * await bru.cookies.delete('sid');
   */
  delete(name: string, callback?: (error?: Error | undefined) => void): void | Promise<void>;
  /**
   * Get the cookie jar, to read and write the cookies of any URL.
   *
   * Every URL argument may contain `{{variables}}`.
   *
   * @returns The jar.
   * @category Jar
   * @example
   * const jar = bru.cookies.jar();
   *
   * // Read a cookie from a different URL
   * const token = await jar.getCookie('{{authBaseUrl}}/login', 'access_token');
   *
   * // Set a cookie on a specific URL
   * await jar.setCookie('{{apiBaseUrl}}', { key: 'sid', value: 'abc' });
   * await jar.setCookie('{{apiBaseUrl}}', 'theme', 'dark');
   *
   * // Check if a cookie exists
   * const exists = await jar.hasCookie('{{apiBaseUrl}}', 'sid');
   *
   * // Clear ALL cookies globally
   * await jar.clear();
   */
  jar(): CookieJar;
  /**
   * Get the value of the entry with the given key.
   *
   * With several entries of that key, the last enabled one wins.
   *
   * @param name - The key.
   * @returns The entry's value, or `undefined` when there is none.
   * @example
   * const contentType = req.headerList.get('content-type');
   * @category Read
   */
  get(name: string): any;
  /**
   * Get the whole entry with the given key.
   *
   * With several entries of that key, the last enabled one wins.
   *
   * @param name - The key.
   * @returns The entry, or `undefined` when there is none.
   * @category Read
   */
  one(name: string): Cookie | undefined;
  /**
   * Get every entry, in order.
   *
   * @returns A new array of the entries.
   * @category Read
   */
  all(): Cookie[];
  /**
   * Get the entry at a position in the list.
   *
   * @param index - The zero-based position.
   * @returns The entry, or `undefined` past the end of the list.
   * @category Read
   */
  idx(index: number): Cookie | undefined;
  /**
   * Count the entries.
   *
   * @returns How many entries the list has.
   * @category Read
   */
  count(): number;
  /**
   * Find the position of an entry, by key or by an entry object.
   *
   * A key finds the first entry with that key. An entry object matches on both key and value,
   * so a copy of an entry finds it too.
   *
   * @param nameOrItem - A key, or an entry.
   * @returns The zero-based position, or `-1` when there is no match.
   * @category Search
   */
  indexOf(nameOrItem: string | Cookie): number;
  /**
   * Check whether an entry with the given key exists, optionally with a given value.
   *
   * @param nameOrItem - A key, or an entry whose key to look for.
   * @param value - When given, the entry's value must equal it too.
   * @returns `true` when a matching entry exists.
   * @example
   * if (!req.headerList.has('Authorization')) {
   *   req.headerList.upsert({ key: 'Authorization', value: 'Bearer …' });
   * }
   * @category Search
   */
  has(nameOrItem: string | Cookie, value?: any): boolean;
  /**
   * Find the first entry a predicate accepts.
   *
   * @param predicate - Called with each entry and its position.
   * @param context - The `this` of `predicate`.
   * @returns The entry, or `undefined` when none matches.
   * @category Search
   */
  find(predicate: (item: Cookie, index: number) => unknown, context?: any): Cookie | undefined;
  /**
   * Get every entry a predicate accepts.
   *
   * @param predicate - Called with each entry and its position.
   * @param context - The `this` of `predicate`.
   * @returns The matching entries, in order.
   * @category Search
   */
  filter(predicate: (item: Cookie, index: number) => unknown, context?: any): Cookie[];
  /**
   * Call a function for every entry, in order.
   *
   * @param fn - Called with each entry and its position.
   * @param context - The `this` of `fn`.
   * @category Iteration
   */
  each(fn: (item: Cookie, index: number) => void, context?: any): void;
  /**
   * Turn every entry into a new value.
   *
   * @param fn - Called with each entry and its position.
   * @param context - The `this` of `fn`.
   * @returns What `fn` returned for each entry, in order.
   * @example
   * const names = req.headerList.map((header) => header.key);
   * @category Iteration
   */
  map(fn: (item: Cookie, index: number) => any, context?: any): any[];
  /**
   * Combine the entries into a single value, like `Array.prototype.reduce`.
   *
   * @param fn - Called with the value so far, each entry and its position.
   * @param initialValue - The starting value. Without it, the first entry is.
   * @param context - The `this` of `fn`.
   * @returns The last value `fn` returned.
   * @category Iteration
   */
  reduce(fn: (accumulator: any, item: Cookie, index: number) => any, initialValue?: any, context?: any): any;
  /**
   * Convert the list to a `{ key: value }` object. With several entries of a key, the last wins.
   *
   * @returns The values, by key.
   * @category Transform
   */
  toObject(): Record<string, any>;
  /**
   * Convert the list to a `key=value; key2=value2` string.
   *
   * @returns The entries, separated by `; `.
   * @category Transform
   */
  toString(): string;
  /**
   * Get the entries for `JSON.stringify()`; the same as `all()`.
   *
   * @returns A new array of the entries.
   * @category Transform
   */
  toJSON(): Cookie[];
}

/**
 * Controls for the collection runner.
 *
 * @category bru
 */
export interface Runner {
  /**
   * - Skip the current request. Call it from a pre-request script; the request is not sent and is reported as skipped.
   */
  skipRequest(): void;
  /**
   * - Stop the collection run once the current request finishes. No further requests are run.
   */
  stopExecution(): void;
  /**
   * - Choose the request the runner runs next, by its name. `null` ends the run after the current request.
   */
  setNextRequest(requestName: string | null): void;
}

/**
 * Helpers for formatting payloads.
 *
 * @category bru
 */
export interface ScriptUtils {
  /**
   * - Minify JSON: strip all whitespace from a JSON string, or serialize an object without any. Throws on invalid JSON.
   */
  minifyJson(json: string | object): string;
  /**
   * - Minify an XML string by removing the whitespace between tags. Throws on invalid XML.
   */
  minifyXml(xml: string): string;
}

/**
 * The response of a collection request run with `bru.runRequest()`.
 *
 * @category bru
 */
export interface RunRequestResponse {
  /**
   * - The HTTP status code, or `'skipped'` for a request that can't be run from a script (WebSocket and gRPC requests).
   */
  status: string | number;
  /**
   * - The HTTP status text, or why the request was skipped.
   */
  statusText: string;
  /**
   * - The response headers.
   */
  headers: Record<string, string | string[]>;
  /**
   * - The response body.
   */
  data: any;
  /**
   * - How long the request took, in milliseconds.
   */
  duration: number;
  /**
   * - The size of the response, in bytes.
   */
  size: number;
}

/**
 * The `test()` results of the current script so far.
 *
 * @category bru
 */
export interface TestResults {
  /**
   * - Pass and fail counts.
   */
  summary: ResultsSummary;
  /**
   * - One entry per test, in the order they finished.
   */
  results: TestResult[];
}

/**
 * The results of the request's Assert tab.
 *
 * @category bru
 */
export interface AssertionResults {
  /**
   * - Pass and fail counts.
   */
  summary: ResultsSummary;
  /**
   * - One entry per assertion.
   */
  results: AssertionResult[];
}

/**
 * The gRPC call a hook runs in, as `bru.grpc`.
 *
 * @category bru.grpc
 */
export interface Grpc {
  /**
   * The call's request: target, method, metadata and the messages sent.
   *
   * @category gRPC
   */
  readonly request: GrpcRequest;
  /**
   * What the server has answered so far: status, metadata, trailers and messages.
   *
   * In `afterMessageReceive` the call is still open, so the status, duration and trailers are not
   * known yet.
   *
   * @context grpc:after-message-receive grpc:after-call-end
   * @category gRPC
   */
  readonly response?: GrpcResponse;
}

/**
 * A path parameter of the request, such as `id` in `/users/:id`.
 *
 * @category req
 */
export interface PathParam {
  /**
   * - The parameter's name, without the leading `:`.
   */
  name: string;
  /**
   * - Its value.
   */
  value: string;
  /**
   * - Always `'path'`.
   */
  type: string;
}

/**
 * The headers of a request, as a list of `{ key, value, disabled? }` entries.
 *
 * Keys match case-insensitively, as HTTP header names do. Headers disabled in the request's
 * Headers tab are in the list with `disabled: true` and are not sent.
 *
 * @category req
 */
export interface HeaderList {
  /**
   * Set a header, replacing any header of the same name.
   *
   * Takes a header object, a `'Name: value'` string, or the name and value as two arguments.
   *
   * @param itemOrName - A header, a `'Name: value'` string, or the header's name.
   * @param value - The header's value, when `itemOrName` is its name.
   * @example
   * req.headerList.add({ key: 'X-Request-Id', value: bru.getVar('requestId') });
   * req.headerList.add('Accept: application/json');
   * @category Write
   */
  add(itemOrName: string | Header, value?: any): void;
  /**
   * Set a header, replacing any header of the same name, and report whether it was new.
   *
   * A header written with `disabled: true` stays in the list but is not sent; any other write
   * enables it.
   *
   * @param itemOrName - A header, or the header's name.
   * @param value - The header's value, when `itemOrName` is its name.
   * @returns `true` when the header was added, `false` when it replaced one, and `null` when no header was given.
   * @example
   * req.headerList.upsert({ key: 'Authorization', value: `Bearer ${bru.getVar('token')}` });
   * @category Write
   */
  upsert(itemOrName: string | Header, value?: any): boolean | null;
  /**
   * Remove headers by name, by a header object's name, or by a predicate.
   *
   * Removing a default header such as `User-Agent` keeps it from being sent at all.
   *
   * @param predicate - A header name, a header, or a function that returns `true` for each header to remove.
   * @param context - The `this` of a function `predicate`.
   * @example
   * req.headerList.remove('X-Debug');
   * req.headerList.remove((header) => header.key.startsWith('X-Internal-'));
   * @category Write
   */
  remove(predicate: string | Header | ((header: Header) => unknown), context?: any): void;
  /**
   * Remove every header, disabled ones included.
   *
   * @category Write
   */
  clear(): void;
  /**
   * Add headers that aren't set yet; a header whose name is already in the list is skipped.
   *
   * @param items - Headers, or `'Name: value'` lines.
   * @example
   * req.headerList.populate('Accept: application/json\nX-Client: bruno');
   * @category Write
   */
  populate(items: string | Header[]): void;
  /**
   * Replace every header with the given ones.
   *
   * @param items - Headers, or `'Name: value'` lines.
   * @category Write
   */
  repopulate(items: string | Header[]): void;
  /**
   * Set every header of another list, replacing headers of the same name.
   *
   * @param source - Another header list, such as `res.headerList`, or an array of headers.
   * @param prune - Also remove the headers `source` doesn't have.
   * @category Write
   */
  assimilate(source: ReadOnlyHeaderList | Header[], prune?: boolean): void;
  /**
   * Convert the headers to a `{ name: value }` object.
   *
   * An enabled header wins over a disabled one of the same name.
   *
   * @param excludeDisabled - Leave out disabled headers.
   * @param caseSensitive - `false` lower-cases every name.
   * @param multiValue - Keep the first value of a repeated name instead of the last.
   * @param sanitizeKeys - Leave out headers with an empty name.
   * @returns The values, by header name.
   * @example
   * const headers = req.headerList.toObject(true);
   * @category Transform
   */
  toObject(excludeDisabled?: boolean, caseSensitive?: boolean, multiValue?: boolean, sanitizeKeys?: boolean): Record<string, any>;
  /**
   * Convert the enabled headers to HTTP format: one `Name: value` line per header.
   *
   * @returns The header lines, each ending in a newline; `''` when there are none.
   * @category Transform
   */
  toString(): string;
  /**
   * Get the value of the entry with the given key.
   *
   * With several entries of that key, the last enabled one wins.
   *
   * @param name - The key.
   * @returns The entry's value, or `undefined` when there is none.
   * @example
   * const contentType = req.headerList.get('content-type');
   * @category Read
   */
  get(name: string): any;
  /**
   * Get the whole entry with the given key.
   *
   * With several entries of that key, the last enabled one wins.
   *
   * @param name - The key.
   * @returns The entry, or `undefined` when there is none.
   * @category Read
   */
  one(name: string): Header | undefined;
  /**
   * Get every entry, in order.
   *
   * @returns A new array of the entries.
   * @category Read
   */
  all(): Header[];
  /**
   * Get the entry at a position in the list.
   *
   * @param index - The zero-based position.
   * @returns The entry, or `undefined` past the end of the list.
   * @category Read
   */
  idx(index: number): Header | undefined;
  /**
   * Count the entries.
   *
   * @returns How many entries the list has.
   * @category Read
   */
  count(): number;
  /**
   * Find the position of an entry, by key or by an entry object.
   *
   * A key finds the first entry with that key. An entry object matches on both key and value,
   * so a copy of an entry finds it too.
   *
   * @param nameOrItem - A key, or an entry.
   * @returns The zero-based position, or `-1` when there is no match.
   * @category Search
   */
  indexOf(nameOrItem: string | Header): number;
  /**
   * Check whether an entry with the given key exists, optionally with a given value.
   *
   * @param nameOrItem - A key, or an entry whose key to look for.
   * @param value - When given, the entry's value must equal it too.
   * @returns `true` when a matching entry exists.
   * @example
   * if (!req.headerList.has('Authorization')) {
   *   req.headerList.upsert({ key: 'Authorization', value: 'Bearer …' });
   * }
   * @category Search
   */
  has(nameOrItem: string | Header, value?: any): boolean;
  /**
   * Find the first entry a predicate accepts.
   *
   * @param predicate - Called with each entry and its position.
   * @param context - The `this` of `predicate`.
   * @returns The entry, or `undefined` when none matches.
   * @category Search
   */
  find(predicate: (item: Header, index: number) => unknown, context?: any): Header | undefined;
  /**
   * Get every entry a predicate accepts.
   *
   * @param predicate - Called with each entry and its position.
   * @param context - The `this` of `predicate`.
   * @returns The matching entries, in order.
   * @category Search
   */
  filter(predicate: (item: Header, index: number) => unknown, context?: any): Header[];
  /**
   * Call a function for every entry, in order.
   *
   * @param fn - Called with each entry and its position.
   * @param context - The `this` of `fn`.
   * @category Iteration
   */
  each(fn: (item: Header, index: number) => void, context?: any): void;
  /**
   * Turn every entry into a new value.
   *
   * @param fn - Called with each entry and its position.
   * @param context - The `this` of `fn`.
   * @returns What `fn` returned for each entry, in order.
   * @example
   * const names = req.headerList.map((header) => header.key);
   * @category Iteration
   */
  map(fn: (item: Header, index: number) => any, context?: any): any[];
  /**
   * Combine the entries into a single value, like `Array.prototype.reduce`.
   *
   * @param fn - Called with the value so far, each entry and its position.
   * @param initialValue - The starting value. Without it, the first entry is.
   * @param context - The `this` of `fn`.
   * @returns The last value `fn` returned.
   * @category Iteration
   */
  reduce(fn: (accumulator: any, item: Header, index: number) => any, initialValue?: any, context?: any): any;
  /**
   * Get the entries for `JSON.stringify()`; the same as `all()`.
   *
   * @returns A new array of the entries.
   * @category Transform
   */
  toJSON(): Header[];
}

/**
 * The read-only header list of a response.
 *
 * @category res
 */
export interface ReadOnlyHeaderList {
  /**
   * Convert the enabled headers to HTTP format: one `Name: value` line per header.
   *
   * @returns The header lines, each ending in a newline; `''` when there are none.
   * @category Transform
   */
  toString(): string;
  /**
   * Convert the headers to a `{ name: value }` object.
   *
   * An enabled header wins over a disabled one of the same name.
   *
   * @param excludeDisabled - Leave out disabled headers.
   * @param caseSensitive - `false` lower-cases every name.
   * @param multiValue - Keep the first value of a repeated name instead of the last.
   * @param sanitizeKeys - Leave out headers with an empty name.
   * @returns The values, by header name.
   * @example
   * const headers = req.headerList.toObject(true);
   * @category Transform
   */
  toObject(excludeDisabled?: boolean, caseSensitive?: boolean, multiValue?: boolean, sanitizeKeys?: boolean): Record<string, any>;
  /**
   * Get the value of the entry with the given key.
   *
   * With several entries of that key, the last enabled one wins.
   *
   * @param name - The key.
   * @returns The entry's value, or `undefined` when there is none.
   * @example
   * const contentType = req.headerList.get('content-type');
   * @category Read
   */
  get(name: string): any;
  /**
   * Get the whole entry with the given key.
   *
   * With several entries of that key, the last enabled one wins.
   *
   * @param name - The key.
   * @returns The entry, or `undefined` when there is none.
   * @category Read
   */
  one(name: string): Header | undefined;
  /**
   * Get every entry, in order.
   *
   * @returns A new array of the entries.
   * @category Read
   */
  all(): Header[];
  /**
   * Get the entry at a position in the list.
   *
   * @param index - The zero-based position.
   * @returns The entry, or `undefined` past the end of the list.
   * @category Read
   */
  idx(index: number): Header | undefined;
  /**
   * Count the entries.
   *
   * @returns How many entries the list has.
   * @category Read
   */
  count(): number;
  /**
   * Find the position of an entry, by key or by an entry object.
   *
   * A key finds the first entry with that key. An entry object matches on both key and value,
   * so a copy of an entry finds it too.
   *
   * @param nameOrItem - A key, or an entry.
   * @returns The zero-based position, or `-1` when there is no match.
   * @category Search
   */
  indexOf(nameOrItem: string | Header): number;
  /**
   * Check whether an entry with the given key exists, optionally with a given value.
   *
   * @param nameOrItem - A key, or an entry whose key to look for.
   * @param value - When given, the entry's value must equal it too.
   * @returns `true` when a matching entry exists.
   * @example
   * if (!req.headerList.has('Authorization')) {
   *   req.headerList.upsert({ key: 'Authorization', value: 'Bearer …' });
   * }
   * @category Search
   */
  has(nameOrItem: string | Header, value?: any): boolean;
  /**
   * Find the first entry a predicate accepts.
   *
   * @param predicate - Called with each entry and its position.
   * @param context - The `this` of `predicate`.
   * @returns The entry, or `undefined` when none matches.
   * @category Search
   */
  find(predicate: (item: Header, index: number) => unknown, context?: any): Header | undefined;
  /**
   * Get every entry a predicate accepts.
   *
   * @param predicate - Called with each entry and its position.
   * @param context - The `this` of `predicate`.
   * @returns The matching entries, in order.
   * @category Search
   */
  filter(predicate: (item: Header, index: number) => unknown, context?: any): Header[];
  /**
   * Call a function for every entry, in order.
   *
   * @param fn - Called with each entry and its position.
   * @param context - The `this` of `fn`.
   * @category Iteration
   */
  each(fn: (item: Header, index: number) => void, context?: any): void;
  /**
   * Turn every entry into a new value.
   *
   * @param fn - Called with each entry and its position.
   * @param context - The `this` of `fn`.
   * @returns What `fn` returned for each entry, in order.
   * @example
   * const names = req.headerList.map((header) => header.key);
   * @category Iteration
   */
  map(fn: (item: Header, index: number) => any, context?: any): any[];
  /**
   * Combine the entries into a single value, like `Array.prototype.reduce`.
   *
   * @param fn - Called with the value so far, each entry and its position.
   * @param initialValue - The starting value. Without it, the first entry is.
   * @param context - The `this` of `fn`.
   * @returns The last value `fn` returned.
   * @category Iteration
   */
  reduce(fn: (accumulator: any, item: Header, index: number) => any, initialValue?: any, context?: any): any;
  /**
   * Get the entries for `JSON.stringify()`; the same as `all()`.
   *
   * @returns A new array of the entries.
   * @category Transform
   */
  toJSON(): Header[];
}

/**
 * The size of a response, in bytes.
 *
 * @category res
 */
export interface ResponseSize {
  /**
   * - The size of the status line and headers.
   */
  header: number;
  /**
   * - The size of the body as received.
   */
  body: number;
  /**
   * - `header + body`.
   */
  total: number;
}

/**
 * A cookie to write to the jar. `domain` defaults to the URL's host and `path` to `/`.
 *
 * @category bru
 */
export interface CookieInput {
  /**
   * - The cookie's name.
   */
  key: string;
  /**
   * - Its value.
   */
  value: string;
  /**
   * - The domain to send it to.
   */
  domain?: string;
  /**
   * - The path to send it to.
   */
  path?: string;
  /**
   * - Only send it over HTTPS.
   */
  secure?: boolean;
  /**
   * - Hide it from browser scripts.
   */
  httpOnly?: boolean;
  /**
   * - When it expires. Without it, it never does.
   */
  expires?: string | number | Date;
  /**
   * - How many seconds it lives.
   */
  maxAge?: number;
  /**
   * - The SameSite policy.
   */
  sameSite?: "none" | "strict" | "lax";
}

/**
 * Cookies of any URL. Every method takes the URL first, which may contain `{{variables}}`, and
 * returns a promise, or calls `callback` instead when one is passed.
 *
 * @category bru
 */
export interface CookieJar {
  /**
   * - Get the cookie with the given name that would be sent to the URL, or `null`.
   */
  getCookie(url: string, name: string): Promise<Cookie | null>;
  /**
   * - Get the cookie with the given name that would be sent to the URL, or `null`.
   */
  getCookie(url: string, name: string, callback: (error: Error | null, cookie?: Cookie | null | undefined) => void): void;
  /**
   * - Get every cookie that would be sent to the URL.
   */
  getCookies(url: string): Promise<Cookie[]>;
  /**
   * - Get every cookie that would be sent to the URL.
   */
  getCookies(url: string, callback: (error: Error | null, cookies?: Cookie[] | undefined) => void): void;
  /**
   * - Set a cookie for the URL, from a cookie object or a name and value.
   */
  setCookie(url: string, cookie: CookieInput): Promise<void>;
  /**
   * - Set a cookie for the URL, from a cookie object or a name and value.
   */
  setCookie(url: string, cookie: CookieInput, callback: (error?: Error | undefined) => void): void;
  /**
   * - Set a cookie for the URL, from a cookie object or a name and value.
   */
  setCookie(url: string, name: string, value: string): Promise<void>;
  /**
   * - Set a cookie for the URL, from a cookie object or a name and value.
   */
  setCookie(url: string, name: string, value: string, callback: (error?: Error | undefined) => void): void;
  /**
   * - Set several cookies for the URL.
   */
  setCookies(url: string, cookies: CookieInput[]): Promise<void>;
  /**
   * - Set several cookies for the URL.
   */
  setCookies(url: string, cookies: CookieInput[], callback: (error?: Error | undefined) => void): void;
  /**
   * - Check whether a cookie with the given name would be sent to the URL.
   */
  hasCookie(url: string, name: string): Promise<boolean>;
  /**
   * - Check whether a cookie with the given name would be sent to the URL.
   */
  hasCookie(url: string, name: string, callback: (error: Error | null, exists?: boolean | undefined) => void): void;
  /**
   * - Delete the cookie with the given name for the URL.
   */
  deleteCookie(url: string, name: string): Promise<void>;
  /**
   * - Delete the cookie with the given name for the URL.
   */
  deleteCookie(url: string, name: string, callback: (error?: Error | undefined) => void): void;
  /**
   * - Delete every cookie that would be sent to the URL.
   */
  deleteCookies(url: string): Promise<void>;
  /**
   * - Delete every cookie that would be sent to the URL.
   */
  deleteCookies(url: string, callback: (error?: Error | undefined) => void): void;
  /**
   * - Delete every cookie in the jar, for every URL.
   */
  clear(): Promise<void>;
  /**
   * - Delete every cookie in the jar, for every URL.
   */
  clear(callback: (error?: Error | undefined) => void): void;
}

/**
 * A cookie in the cookie jar.
 *
 * @category bru
 */
export interface Cookie {
  /**
   * - The cookie's name.
   */
  key: string;
  /**
   * - Its value.
   */
  value: string;
  /**
   * - The domain it is sent to.
   */
  domain?: string;
  /**
   * - The path it is sent to.
   */
  path?: string;
  /**
   * - Whether it is only sent over HTTPS.
   */
  secure?: boolean;
  /**
   * - Whether it is hidden from browser scripts.
   */
  httpOnly?: boolean;
  /**
   * - When it expires; `'Infinity'` for a session cookie.
   */
  expires?: Date | "Infinity";
}

/**
 * Pass and fail counts of a set of results.
 *
 * @category bru
 */
export interface ResultsSummary {
  /**
   * - How many results there are.
   */
  total: number;
  /**
   * - How many passed.
   */
  passed: number;
  /**
   * - How many failed.
   */
  failed: number;
  /**
   * - How many were skipped.
   */
  skipped: number;
}

/**
 * One `test()` result.
 *
 * @category bru
 */
export interface TestResult {
  /**
   * - The outcome.
   */
  status: "pass" | "fail" | "skip";
  /**
   * - The name the test was declared with.
   */
  description: string;
  /**
   * - The expected value, for a failed assertion.
   */
  expected?: any;
  /**
   * - The actual value, for a failed assertion.
   */
  actual?: any;
  /**
   * - The failure message.
   */
  error?: string;
}

/**
 * One result of the request's Assert tab.
 *
 * @category bru
 */
export interface AssertionResult {
  /**
   * - The outcome.
   */
  status: "pass" | "fail";
  /**
   * - The expression asserted on, such as `res.status`.
   */
  lhsExpr: string;
  /**
   * - The assertion as written, such as `eq 200`.
   */
  rhsExpr: string;
  /**
   * - The assertion's operator, such as `eq`.
   */
  operator: string;
  /**
   * - The value the expression was compared with.
   */
  rhsOperand: any;
  /**
   * - The failure message.
   */
  error?: string;
}

/**
 * The request of the gRPC call, as `bru.grpc.request`.
 *
 * @category bru.grpc
 */
export interface GrpcRequest {
  /**
   * The server URL, as written in the request: `{{variables}}` are not interpolated.
   *
   * @category Call
   */
  readonly url: string;
  /**
   * The full method path, such as `'/helloworld.Greeter/SayHello'`.
   *
   * @category Call
   */
  readonly method: string;
  /**
   * The kind of call.
   *
   * @category Call
   */
  readonly methodType: "unary" | "client-streaming" | "server-streaming" | "bidi-streaming";
  /**
   * The kind of authentication the call uses, such as `'bearer'`, or `'none'`.
   *
   * @category Call
   */
  readonly authMode: string;
  /**
   * The path of the `.proto` file the call uses, or `undefined` with server reflection.
   *
   * @category Call
   */
  readonly protoPath: string | undefined;
  /**
   * The request's name, as shown in the sidebar.
   *
   * @category Call
   */
  readonly name: string;
  /**
   * The call's metadata. It can only be changed in `beforeCallStart`, before the call is sent.
   *
   * @example
   * bru.grpc.request.metadata.upsert('authorization', `Bearer ${bru.getVar('token')}`);
   * @category Metadata
   */
  readonly metadata: GrpcMetadataList;
  /**
   * The messages the call has sent so far; empty in `beforeCallStart`.
   *
   * @category Messages
   */
  readonly messages: GrpcMessageList;
  /**
   * The message about to be sent.
   *
   * @context grpc:before-message-send
   * @category Messages
   */
  readonly message: GrpcMessage;
}

/**
 * What the gRPC server has answered so far, as `bru.grpc.response`.
 *
 * @category bru.grpc
 */
export interface GrpcResponse {
  /**
   * The gRPC status code: `0` for OK. `undefined` while the call is still open.
   *
   * @category Status
   */
  readonly statusCode: number | undefined;
  /**
   * The gRPC status message. `undefined` while the call is still open.
   *
   * @category Status
   */
  readonly statusText: string | undefined;
  /**
   * The messages received so far.
   *
   * @category Messages
   */
  readonly messages: GrpcMessageList;
  /**
   * The metadata the server sent before its first message.
   *
   * @category Metadata
   */
  readonly metadata: ReadOnlyGrpcMetadataList;
  /**
   * The metadata the server sent when it ended the call. Empty while the call is still open.
   *
   * @category Metadata
   */
  readonly trailers: ReadOnlyGrpcMetadataList;
  /**
   * How long the call took, in milliseconds. `undefined` while the call is still open.
   *
   * @category Status
   */
  readonly duration: number | undefined;
  /**
   * The message just received; also the last entry of `messages`.
   *
   * @context grpc:after-message-receive
   * @category Messages
   */
  readonly message: GrpcMessage;
}

/**
 * A header of the request or the response.
 *
 * @category req
 */
export interface Header {
  /**
   * - The header's name, in the case it was written in.
   */
  key: string;
  /**
   * - The header's value; an array of values for a repeated response header.
   */
  value: any;
  /**
   * - `true` for a header switched off in the request's Headers tab. It is not sent.
   */
  disabled?: boolean;
}

/**
 * gRPC metadata, as a list of `{ key, value, disabled? }` entries. Keys match case-insensitively.
 *
 * @category bru.grpc
 */
export interface GrpcMetadataList {
  /**
   * Convert the enabled entries to `key: value` lines, the way metadata travels as HTTP/2 headers.
   *
   * @returns One line per entry.
   * @category Transform
   */
  toString(): string;
  /**
   * Set a metadata entry, replacing one with the same key in any case. The entry ends up enabled.
   *
   * @param key - The metadata key.
   * @param value - Its value.
   * @example
   * bru.grpc.request.metadata.upsert('x-request-id', bru.getVar('requestId'));
   * @context grpc:before-call-start
   * @category Write
   */
  upsert(key: string, value: any): void;
  /**
   * Set a metadata entry from an entry object, such as one read from another list.
   *
   * @param item - The entry. `disabled: true` keeps it from being sent.
   * @context grpc:before-call-start
   * @category Write
   */
  add(item: MetadataEntry): void;
  /**
   * Remove the entry with the given key, enabled or disabled.
   *
   * @param key - The metadata key.
   * @context grpc:before-call-start
   * @category Write
   */
  remove(key: string): void;
  /**
   * Remove every entry, enabled and disabled.
   *
   * @context grpc:before-call-start
   * @category Write
   */
  clear(): void;
  /**
   * Get the value of the entry with the given key.
   *
   * With several entries of that key, the last enabled one wins.
   *
   * @param name - The key.
   * @returns The entry's value, or `undefined` when there is none.
   * @example
   * const contentType = req.headerList.get('content-type');
   * @category Read
   */
  get(name: string): any;
  /**
   * Get the whole entry with the given key.
   *
   * With several entries of that key, the last enabled one wins.
   *
   * @param name - The key.
   * @returns The entry, or `undefined` when there is none.
   * @category Read
   */
  one(name: string): MetadataEntry | undefined;
  /**
   * Get every entry, in order.
   *
   * @returns A new array of the entries.
   * @category Read
   */
  all(): MetadataEntry[];
  /**
   * Get the entry at a position in the list.
   *
   * @param index - The zero-based position.
   * @returns The entry, or `undefined` past the end of the list.
   * @category Read
   */
  idx(index: number): MetadataEntry | undefined;
  /**
   * Count the entries.
   *
   * @returns How many entries the list has.
   * @category Read
   */
  count(): number;
  /**
   * Find the position of an entry, by key or by an entry object.
   *
   * A key finds the first entry with that key. An entry object matches on both key and value,
   * so a copy of an entry finds it too.
   *
   * @param nameOrItem - A key, or an entry.
   * @returns The zero-based position, or `-1` when there is no match.
   * @category Search
   */
  indexOf(nameOrItem: string | MetadataEntry): number;
  /**
   * Check whether an entry with the given key exists, optionally with a given value.
   *
   * @param nameOrItem - A key, or an entry whose key to look for.
   * @param value - When given, the entry's value must equal it too.
   * @returns `true` when a matching entry exists.
   * @example
   * if (!req.headerList.has('Authorization')) {
   *   req.headerList.upsert({ key: 'Authorization', value: 'Bearer …' });
   * }
   * @category Search
   */
  has(nameOrItem: string | MetadataEntry, value?: any): boolean;
  /**
   * Find the first entry a predicate accepts.
   *
   * @param predicate - Called with each entry and its position.
   * @param context - The `this` of `predicate`.
   * @returns The entry, or `undefined` when none matches.
   * @category Search
   */
  find(predicate: (item: MetadataEntry, index: number) => unknown, context?: any): MetadataEntry | undefined;
  /**
   * Get every entry a predicate accepts.
   *
   * @param predicate - Called with each entry and its position.
   * @param context - The `this` of `predicate`.
   * @returns The matching entries, in order.
   * @category Search
   */
  filter(predicate: (item: MetadataEntry, index: number) => unknown, context?: any): MetadataEntry[];
  /**
   * Call a function for every entry, in order.
   *
   * @param fn - Called with each entry and its position.
   * @param context - The `this` of `fn`.
   * @category Iteration
   */
  each(fn: (item: MetadataEntry, index: number) => void, context?: any): void;
  /**
   * Turn every entry into a new value.
   *
   * @param fn - Called with each entry and its position.
   * @param context - The `this` of `fn`.
   * @returns What `fn` returned for each entry, in order.
   * @example
   * const names = req.headerList.map((header) => header.key);
   * @category Iteration
   */
  map(fn: (item: MetadataEntry, index: number) => any, context?: any): any[];
  /**
   * Combine the entries into a single value, like `Array.prototype.reduce`.
   *
   * @param fn - Called with the value so far, each entry and its position.
   * @param initialValue - The starting value. Without it, the first entry is.
   * @param context - The `this` of `fn`.
   * @returns The last value `fn` returned.
   * @category Iteration
   */
  reduce(fn: (accumulator: any, item: MetadataEntry, index: number) => any, initialValue?: any, context?: any): any;
  /**
   * Convert the list to a `{ key: value }` object. With several entries of a key, the last wins.
   *
   * @returns The values, by key.
   * @category Transform
   */
  toObject(): Record<string, any>;
  /**
   * Get the entries for `JSON.stringify()`; the same as `all()`.
   *
   * @returns A new array of the entries.
   * @category Transform
   */
  toJSON(): MetadataEntry[];
}

/**
 * The messages of a gRPC call, in the order they were sent or received. Read-only.
 *
 * @category bru.grpc
 */
export interface GrpcMessageList {
  /**
   * Get every message, in order.
   *
   * @returns A new array of the messages.
   * @category Read
   */
  all(): GrpcMessage[];
  /**
   * Get the message at a position. Unary and client-to-server calls send exactly one, at `0`.
   *
   * @param index - The zero-based position; `0` when left out.
   * @returns The message, or `undefined` past the end of the list.
   * @example
   * const reply = bru.grpc.response.messages.get().data;
   * @category Read
   */
  get(index?: number): GrpcMessage | undefined;
  /**
   * Count the messages.
   *
   * @returns How many messages the list has.
   * @category Read
   */
  count(): number;
  /**
   * Find the first message a predicate accepts.
   *
   * @param fn - Called with each message and its position.
   * @param context - The `this` of `fn`.
   * @returns The message, or `undefined` when none matches.
   * @category Search
   */
  find(fn: (message: GrpcMessage, index: number) => unknown, context?: any): GrpcMessage | undefined;
  /**
   * Get every message a predicate accepts.
   *
   * @param fn - Called with each message and its position.
   * @param context - The `this` of `fn`.
   * @returns The matching messages, in order.
   * @category Search
   */
  filter(fn: (message: GrpcMessage, index: number) => unknown, context?: any): GrpcMessage[];
  /**
   * Turn every message into a new value.
   *
   * @param fn - Called with each message and its position.
   * @param context - The `this` of `fn`.
   * @returns What `fn` returned for each message, in order.
   * @category Iteration
   */
  map(fn: (message: GrpcMessage, index: number) => any, context?: any): any[];
  /**
   * Call a function for every message, in order.
   *
   * @param fn - Called with each message and its position.
   * @param context - The `this` of `fn`.
   * @category Iteration
   */
  each(fn: (message: GrpcMessage, index: number) => void, context?: any): void;
  /**
   * Combine the messages into a single value, like `Array.prototype.reduce`.
   *
   * @param fn - Called with the value so far, each message and its position.
   * @param initialValue - The starting value. Without it, the first message is.
   * @param context - The `this` of `fn`.
   * @returns The last value `fn` returned.
   * @category Iteration
   */
  reduce(fn: (accumulator: any, message: GrpcMessage, index: number) => any, initialValue?: any, context?: any): any;
  /**
   * Get the messages for `JSON.stringify()`; the same as `all()`.
   *
   * @returns A new array of the messages.
   * @category Transform
   */
  toJSON(): GrpcMessage[];
}

/**
 * A gRPC message: its payload and when it was sent or received.
 *
 * @category bru.grpc
 */
export interface GrpcMessage {
  /**
   * The message payload, as a plain object.
   *
   * @category Message
   */
  readonly data: any;
  /**
   * When the message was sent or received, in milliseconds since the epoch.
   *
   * @category Message
   */
  readonly timestamp: number | undefined;
}

/**
 * The read-only metadata of a gRPC response.
 *
 * @category bru.grpc
 */
export interface ReadOnlyGrpcMetadataList {
  /**
   * Convert the enabled entries to `key: value` lines, the way metadata travels as HTTP/2 headers.
   *
   * @returns One line per entry.
   * @category Transform
   */
  toString(): string;
  /**
   * Convert the list to a `{ key: value }` object. With several entries of a key, the last wins.
   *
   * @returns The values, by key.
   * @category Transform
   */
  toObject(): Record<string, any>;
  /**
   * Get the value of the entry with the given key.
   *
   * With several entries of that key, the last enabled one wins.
   *
   * @param name - The key.
   * @returns The entry's value, or `undefined` when there is none.
   * @example
   * const contentType = req.headerList.get('content-type');
   * @category Read
   */
  get(name: string): any;
  /**
   * Get the whole entry with the given key.
   *
   * With several entries of that key, the last enabled one wins.
   *
   * @param name - The key.
   * @returns The entry, or `undefined` when there is none.
   * @category Read
   */
  one(name: string): MetadataEntry | undefined;
  /**
   * Get every entry, in order.
   *
   * @returns A new array of the entries.
   * @category Read
   */
  all(): MetadataEntry[];
  /**
   * Get the entry at a position in the list.
   *
   * @param index - The zero-based position.
   * @returns The entry, or `undefined` past the end of the list.
   * @category Read
   */
  idx(index: number): MetadataEntry | undefined;
  /**
   * Count the entries.
   *
   * @returns How many entries the list has.
   * @category Read
   */
  count(): number;
  /**
   * Find the position of an entry, by key or by an entry object.
   *
   * A key finds the first entry with that key. An entry object matches on both key and value,
   * so a copy of an entry finds it too.
   *
   * @param nameOrItem - A key, or an entry.
   * @returns The zero-based position, or `-1` when there is no match.
   * @category Search
   */
  indexOf(nameOrItem: string | MetadataEntry): number;
  /**
   * Check whether an entry with the given key exists, optionally with a given value.
   *
   * @param nameOrItem - A key, or an entry whose key to look for.
   * @param value - When given, the entry's value must equal it too.
   * @returns `true` when a matching entry exists.
   * @example
   * if (!req.headerList.has('Authorization')) {
   *   req.headerList.upsert({ key: 'Authorization', value: 'Bearer …' });
   * }
   * @category Search
   */
  has(nameOrItem: string | MetadataEntry, value?: any): boolean;
  /**
   * Find the first entry a predicate accepts.
   *
   * @param predicate - Called with each entry and its position.
   * @param context - The `this` of `predicate`.
   * @returns The entry, or `undefined` when none matches.
   * @category Search
   */
  find(predicate: (item: MetadataEntry, index: number) => unknown, context?: any): MetadataEntry | undefined;
  /**
   * Get every entry a predicate accepts.
   *
   * @param predicate - Called with each entry and its position.
   * @param context - The `this` of `predicate`.
   * @returns The matching entries, in order.
   * @category Search
   */
  filter(predicate: (item: MetadataEntry, index: number) => unknown, context?: any): MetadataEntry[];
  /**
   * Call a function for every entry, in order.
   *
   * @param fn - Called with each entry and its position.
   * @param context - The `this` of `fn`.
   * @category Iteration
   */
  each(fn: (item: MetadataEntry, index: number) => void, context?: any): void;
  /**
   * Turn every entry into a new value.
   *
   * @param fn - Called with each entry and its position.
   * @param context - The `this` of `fn`.
   * @returns What `fn` returned for each entry, in order.
   * @example
   * const names = req.headerList.map((header) => header.key);
   * @category Iteration
   */
  map(fn: (item: MetadataEntry, index: number) => any, context?: any): any[];
  /**
   * Combine the entries into a single value, like `Array.prototype.reduce`.
   *
   * @param fn - Called with the value so far, each entry and its position.
   * @param initialValue - The starting value. Without it, the first entry is.
   * @param context - The `this` of `fn`.
   * @returns The last value `fn` returned.
   * @category Iteration
   */
  reduce(fn: (accumulator: any, item: MetadataEntry, index: number) => any, initialValue?: any, context?: any): any;
  /**
   * Get the entries for `JSON.stringify()`; the same as `all()`.
   *
   * @returns A new array of the entries.
   * @category Transform
   */
  toJSON(): MetadataEntry[];
}

/**
 * An entry of gRPC metadata.
 *
 * @category bru.grpc
 */
export interface MetadataEntry {
  /**
   * - The metadata key, in the case it was written in.
   */
  key: string;
  /**
   * - Its value.
   */
  value: any;
  /**
   * - `true` for an entry switched off in the request's Metadata tab. It is not sent.
   */
  disabled?: boolean;
}
