import {
  SEND_ICON_SVG_TEXT,
  FOLDER_ICON_SVG_TEXT,
  BOX_ICON_SVG_TEXT,
  DATABASE_ICON_SVG_TEXT,
  WORLD_ICON_SVG_TEXT,
  READ_ONLY_SCOPE_ICON
} from 'utils/common/constants';

export const AUTOCOMPLETE_SCOPES = {
  REQUEST: 'request',
  FOLDER: 'folder',
  COLLECTION: 'collection',
  ENVIRONMENT: 'environment',
  GLOBAL: 'global',
  RUNTIME: 'runtime',
  PROCESS_ENV: 'process.env',
  DYNAMIC: 'dynamic',
  OAUTH2: 'oauth2'
};

export const SCOPE_ICON = {
  [AUTOCOMPLETE_SCOPES.REQUEST]: SEND_ICON_SVG_TEXT,
  [AUTOCOMPLETE_SCOPES.FOLDER]: FOLDER_ICON_SVG_TEXT,
  [AUTOCOMPLETE_SCOPES.COLLECTION]: BOX_ICON_SVG_TEXT,
  [AUTOCOMPLETE_SCOPES.ENVIRONMENT]: DATABASE_ICON_SVG_TEXT,
  [AUTOCOMPLETE_SCOPES.GLOBAL]: WORLD_ICON_SVG_TEXT,
  ...READ_ONLY_SCOPE_ICON
};

export const SCOPE_LABEL = {
  [AUTOCOMPLETE_SCOPES.REQUEST]: 'Request',
  [AUTOCOMPLETE_SCOPES.FOLDER]: 'Folder',
  [AUTOCOMPLETE_SCOPES.COLLECTION]: 'Collection',
  [AUTOCOMPLETE_SCOPES.ENVIRONMENT]: 'Environment',
  [AUTOCOMPLETE_SCOPES.GLOBAL]: 'Global',
  [AUTOCOMPLETE_SCOPES.RUNTIME]: 'Runtime',
  [AUTOCOMPLETE_SCOPES.PROCESS_ENV]: 'Process Env',
  [AUTOCOMPLETE_SCOPES.DYNAMIC]: 'Dynamic',
  [AUTOCOMPLETE_SCOPES.OAUTH2]: 'OAuth2'
};

export const SCOPE_ICON_COLOR_CLASS = {
  [AUTOCOMPLETE_SCOPES.REQUEST]: 'request',
  [AUTOCOMPLETE_SCOPES.FOLDER]: 'folder',
  [AUTOCOMPLETE_SCOPES.COLLECTION]: 'collection',
  [AUTOCOMPLETE_SCOPES.ENVIRONMENT]: 'environment',
  [AUTOCOMPLETE_SCOPES.GLOBAL]: 'global',
  [AUTOCOMPLETE_SCOPES.RUNTIME]: 'runtime',
  [AUTOCOMPLETE_SCOPES.PROCESS_ENV]: 'process-env',
  [AUTOCOMPLETE_SCOPES.DYNAMIC]: 'dynamic',
  [AUTOCOMPLETE_SCOPES.OAUTH2]: 'oauth2'
};
