import * as path from 'path';
import * as fs from 'fs';
import type { DatabaseSync } from 'node:sqlite';
import { DB } from '../src/node/db';
import { loadMigrations } from './lib/sources';

const OUTPUT_FILE = path.join(process.cwd(), 'SCHEMA.md');

type TableRow = { name: string; wr: number };
type ColumnRow = { name: string; type: string; notnull: number; dflt_value: string | null; pk: number };
type ForeignKeyRow = { table: string; from: string; to: string | null };
type IndexRow = { name: string; unique: number; origin: string };
type IndexColumnRow = { name: string };

type Table = {
  name: string;
  withoutRowid: boolean;
  columns: ColumnRow[];
  foreignKeys: ForeignKeyRow[];
  indexes: { name: string; unique: boolean; columns: string[] }[];
};

const quote = (identifier: string): string => `"${identifier.replace(/"/g, '""')}"`;

const cell = (value: string): string => value.replace(/\|/g, '\\|');

const mermaidType = (type: string): string => type.match(/^[A-Za-z_][A-Za-z0-9_]*/)?.[0] ?? 'ANY';

const isNotNull = (table: Table, column: ColumnRow): boolean =>
  column.notnull === 1 || (table.withoutRowid && column.pk > 0);

const readTables = (db: DatabaseSync): Table[] => {
  const tables = db
    .prepare(`SELECT name, wr FROM pragma_table_list WHERE schema = 'main' AND type = 'table'
      AND name NOT LIKE 'sqlite_%' AND name <> '_migrations' ORDER BY name`)
    .all() as TableRow[];

  return tables.map(({ name, wr }) => {
    const indexes = (db.prepare(`PRAGMA index_list(${quote(name)})`).all() as IndexRow[])
      .filter((index) => index.origin === 'c')
      .map((index) => ({
        name: index.name,
        unique: index.unique === 1,
        columns: (db.prepare(`PRAGMA index_info(${quote(index.name)})`).all() as IndexColumnRow[]).map((c) => c.name)
      }))
      .sort((a, b) => a.name.localeCompare(b.name));

    return {
      name,
      withoutRowid: wr === 1,
      columns: db.prepare(`PRAGMA table_info(${quote(name)})`).all() as ColumnRow[],
      foreignKeys: db.prepare(`PRAGMA foreign_key_list(${quote(name)})`).all() as ForeignKeyRow[],
      indexes
    };
  });
};

const renderDiagram = (tables: Table[]): string[] => {
  const lines = ['```mermaid', 'erDiagram'];
  for (const table of tables) {
    const foreignKeyColumns = new Set(table.foreignKeys.map((fk) => fk.from));
    lines.push(`  ${table.name} {`);
    for (const column of table.columns) {
      const keys = [column.pk > 0 && 'PK', foreignKeyColumns.has(column.name) && 'FK'].filter(Boolean).join(', ');
      const notNull = isNotNull(table, column) && column.pk === 0 ? ' "NOT NULL"' : '';
      lines.push(`    ${mermaidType(column.type)} ${column.name}${keys ? ` ${keys}` : ''}${notNull}`);
    }
    lines.push('  }');
  }
  for (const table of tables) {
    for (const fk of table.foreignKeys) {
      lines.push(`  ${fk.table} ||--o{ ${table.name} : "${table.name}.${fk.from} -> ${fk.table}.${fk.to ?? 'rowid'}"`);
    }
  }
  lines.push('```');
  return lines;
};

const renderTable = (table: Table): string[] => {
  const lines = [`## \`${table.name}\``, ''];
  if (table.withoutRowid) lines.push('`WITHOUT ROWID`', '');
  lines.push('| Column | Type | Not null | Default | Key |', '|---|---|---|---|---|');
  for (const column of table.columns) {
    const key = column.pk > 0 ? `PK${table.columns.filter((c) => c.pk > 0).length > 1 ? ` (${column.pk})` : ''}` : '';
    lines.push(
      `| \`${column.name}\` | ${cell(column.type) || '—'} | ${isNotNull(table, column) ? 'yes' : ''} | ${
        column.dflt_value === null ? '' : `\`${cell(column.dflt_value)}\``
      } | ${key} |`
    );
  }
  if (table.foreignKeys.length > 0) {
    lines.push('', '**Foreign keys**', '');
    for (const fk of table.foreignKeys) {
      lines.push(`- \`${fk.from}\` → \`${fk.table}.${fk.to ?? 'rowid'}\``);
    }
  }
  if (table.indexes.length > 0) {
    lines.push('', '**Indexes**', '');
    for (const index of table.indexes) {
      lines.push(`- \`${index.name}\`${index.unique ? ' (unique)' : ''} on (${index.columns.map((c) => `\`${c}\``).join(', ')})`);
    }
  }
  lines.push('');
  return lines;
};

const main = () => {
  const migrations = loadMigrations();
  const db = new DB(':memory:', migrations);
  try {
    const tables = readTables(db._db!);
    const lines = [
      '# @usebruno/sqlite schema',
      '',
      '> Generated by `npm run schema` from `migrations/` — do not edit by hand.',
      '',
      `Migrations applied: ${migrations.map((m) => `\`${m.name}\``).join(', ') || 'none'}`,
      '',
      ...renderDiagram(tables),
      '',
      ...tables.flatMap(renderTable)
    ];
    fs.writeFileSync(OUTPUT_FILE, lines.join('\n'));
    console.log(`Wrote the schema of ${tables.length} table(s) to ${path.relative(process.cwd(), OUTPUT_FILE)}.`);
  } finally {
    db._db?.close();
  }
};

main();
