name: 'setup proxy server - linux'
runs:
  using: 'composite'
  steps:
    - name: Setup proxy server
      shell: bash
      run: |
        set -euo pipefail
        
        cd tests/proxy-settings/server
        
        echo "starting proxy server in background"
        node proxy.js &
        
        echo "server started with PID: $!"
