const SIDEBAR_COLLECTION_CLICK = "SIDEBAR_COLLECTION_CLICK";
const SIDEBAR_COLLECTION_ITEM_CLICK = "SIDEBAR_COLLECTION_ITEM_CLICK";
const REQUEST_TAB_CLICK = "REQUEST_TAB_CLICK";
const REQUEST_TAB_CLOSE = "REQUEST_TAB_CLOSE";

export default {
  SIDEBAR_COLLECTION_CLICK,
  SIDEBAR_COLLECTION_ITEM_CLICK,
  REQUEST_TAB_CLICK,
  REQUEST_TAB_CLOSE
};
