name: Feature Request
description: Suggest an idea for this project.
labels: ['enhancement']
body:
  - type: checkboxes
    attributes:
      label: 'I have checked the following:'
      options:
        - label: I've searched existing issues and found nothing related to my issue.
          required: true
  - type: checkboxes
    attributes:
      label: 'This feature'
      options:
        - label: blocks me from using Bruno 
          required: false
        - label: would improve my quality of life in Bruno 
          required: false
        - label: is something I've never seen an API client do before
          required: false
  - type: markdown
    attributes:
      value: |
        Suggest an idea for this project.
  - type: textarea
    attributes:
      label: Describe the feature you want to add, and how it would change your usage of Bruno 
      description: A clear and concise description of the feature you want to be added.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Mockups or Images of the feature
      description: Add some images to support your feature.
    validations:
      required: false
