const SIDEBAR_COLLECTION_CLICK = "SIDEBAR_COLLECTION_CLICK";
const SIDEBAR_COLLECTION_ITEM_CLICK = "SIDEBAR_COLLECTION_ITEM_CLICK";
const SIDEBAR_COLLECTION_ADD_FOLDER = "SIDEBAR_COLLECTION_ADD_FOLDER";
const LOAD_COLLECTIONS_FROM_IDB = "LOAD_COLLECTIONS_FROM_IDB";
const COLLECTION_CREATE = "COLLECTION_CREATE";
const REQUEST_TAB_CLICK = "REQUEST_TAB_CLICK";
const REQUEST_TAB_CLOSE = "REQUEST_TAB_CLOSE";
const REQUEST_URL_CHANGED = "REQUEST_URL_CHANGED";
const REQUEST_GQL_QUERY_CHANGED = "REQUEST_GQL_QUERY_CHANGED";
const RESPONSE_RECEIVED = "RESPONSE_RECEIVED";
const SEND_REQUEST = "SEND_REQUEST";
const SENDING_REQUEST = "SENDING_REQUEST";
const ADD_REQUEST = "ADD_REQUEST";
const ADD_NEW_HTTP_REQUEST = "ADD_NEW_HTTP_REQUEST";
const ADD_NEW_GQL_REQUEST = "ADD_NEW_GQL_REQUEST";
const IDB_CONNECTION_READY = "IDB_CONNECTION_READY";

export default {
  SIDEBAR_COLLECTION_CLICK,
  SIDEBAR_COLLECTION_ITEM_CLICK,
  SIDEBAR_COLLECTION_ADD_FOLDER,
  LOAD_COLLECTIONS_FROM_IDB,
  COLLECTION_CREATE,
  REQUEST_TAB_CLICK,
  REQUEST_TAB_CLOSE,
  REQUEST_URL_CHANGED,
  REQUEST_GQL_QUERY_CHANGED,
  RESPONSE_RECEIVED,
  SEND_REQUEST,
  SENDING_REQUEST,
  ADD_REQUEST,
  ADD_NEW_HTTP_REQUEST,
  ADD_NEW_GQL_REQUEST,
  IDB_CONNECTION_READY
};
