const SIDEBAR_COLLECTION_NEW_REQUEST = "SIDEBAR_COLLECTION_NEW_REQUEST";
const LOAD_COLLECTIONS_FROM_IDB = "LOAD_COLLECTIONS_FROM_IDB";
const REQUEST_GQL_QUERY_CHANGED = "REQUEST_GQL_QUERY_CHANGED";
const ADD_NEW_GQL_REQUEST = "ADD_NEW_GQL_REQUEST";
const IDB_CONNECTION_READY = "IDB_CONNECTION_READY";

export default {
  SIDEBAR_COLLECTION_NEW_REQUEST,
  LOAD_COLLECTIONS_FROM_IDB,
  REQUEST_GQL_QUERY_CHANGED,
  ADD_NEW_GQL_REQUEST,
  IDB_CONNECTION_READY,
};
