const SIDEBAR_COLLECTION_NEW_FOLDER = "SIDEBAR_COLLECTION_NEW_FOLDER";
const SIDEBAR_COLLECTION_NEW_REQUEST = "SIDEBAR_COLLECTION_NEW_REQUEST";
const LOAD_COLLECTIONS_FROM_IDB = "LOAD_COLLECTIONS_FROM_IDB";
const REQUEST_URL_CHANGED = "REQUEST_URL_CHANGED";
const REQUEST_GQL_QUERY_CHANGED = "REQUEST_GQL_QUERY_CHANGED";
const ADD_NEW_GQL_REQUEST = "ADD_NEW_GQL_REQUEST";
const IDB_CONNECTION_READY = "IDB_CONNECTION_READY";
const IDB_COLLECTIONS_SYNC_STARTED = "IDB_COLLECTIONS_SYNC_STARTED";
const IDB_COLLECTIONS_SYNC_ERROR = "IDB_COLLECTIONS_SYNC_ERROR";
const HOTKEY_SAVE = "HOTKEY_SAVE";

export default {
  SIDEBAR_COLLECTION_NEW_FOLDER,
  SIDEBAR_COLLECTION_NEW_REQUEST,
  LOAD_COLLECTIONS_FROM_IDB,
  REQUEST_URL_CHANGED,
  REQUEST_GQL_QUERY_CHANGED,
  ADD_NEW_GQL_REQUEST,
  IDB_CONNECTION_READY,
  IDB_COLLECTIONS_SYNC_STARTED,
  IDB_COLLECTIONS_SYNC_ERROR,
  HOTKEY_SAVE
};
