import { test, Page, ElectronApplication } from '../../../../playwright';

export const buildApiSpecPanelLocators = (page: Page) => ({
  addMenuButton: () => page.getByTestId('api-specs-header-add-menu'),
  openApiSpecMenuItem: () => page.getByTestId('api-specs-header-add-menu-open-api-spec'),
  sidebarItem: (name: string) => page.locator('.api-spec-item').filter({ hasText: name })
});

export const openApiSpecFromDialog = async (
  page: Page,
  electronApp: ElectronApplication,
  filePath: string
): Promise<void> => {
  await test.step(`Open API spec from path: ${filePath}`, async () => {
    await electronApp.evaluate(({ dialog }, filePath) => {
      dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [filePath] });
    }, filePath);

    const { addMenuButton, openApiSpecMenuItem } = buildApiSpecPanelLocators(page);
    await addMenuButton().click();
    await openApiSpecMenuItem().click();
  });
};

export const openApiSpecSidebarItem = async (page: Page, name: string): Promise<void> => {
  await test.step(`Open API spec sidebar item "${name}"`, async () => {
    const { sidebarItem } = buildApiSpecPanelLocators(page);
    await sidebarItem(name).click();
  });
};

const operationLocator = (page: Page, method: string, apiPath: string) =>
  page
    .locator(`.opblock-${method}`)
    .filter({ has: page.locator(`.opblock-summary-path[data-path="${apiPath}"]`) });

export const expandOperation = async (page: Page, method: string, apiPath: string): Promise<void> => {
  await test.step(`Expand ${method.toUpperCase()} ${apiPath} operation`, async () => {
    await operationLocator(page, method, apiPath).locator('.opblock-summary-control').click();
  });
};

// The rendered example is generated by walking the response's schema, so any $ref it
// contains (component schemas, shared responses/parameters) must have already been resolved
// for a referenced property to show up here.
export const operationExampleValue = (page: Page, method: string, apiPath: string, statusCode: string) =>
  operationLocator(page, method, apiPath)
    .locator(`tr.response[data-code="${statusCode}"]`)
    .locator('.model-example .highlight-code');
