name: 'Setup Test Server - macOS'
description: 'Setup Test Server and start test server for custom CA certs tests on macOS'
runs:
  using: 'composite'
  steps:
    - name: Setup Test Server
      shell: bash
      run: |
        set -euo pipefail
        
        cd tests/_server
        
        echo "running certificate setup"
        node scripts/generate-certs.js

    - name: Start test server
      shell: bash
      run: |
        set -euo pipefail
        
        cd tests/_server
        
        echo "starting server in background"
        node index.js &
        
        echo "server started with PID: $!"
