name: Linux Tests
on:
  workflow_dispatch:
  push:
    branches: [main, 'release/v*']
  pull_request:
    branches: [main, 'release/v*']

jobs:
  unit-test:
    name: Unit Tests (Linux)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node Dependencies
        uses: ./.github/actions/common/setup-node-deps

      - name: Run Unit Tests
        uses: ./.github/actions/tests/run-unit-tests
